name: Nx Affected CD
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Deploy NX Affected
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{steps.get-affected-apps.outputs.affected_apps}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx affected -t build --parallel=3 --prod
      - run: echo '::set-output name=affected_apps::$(./node_modules/.bin/nx affected:apps --plain)'
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'eu-west-2'

  deploy-aws-cdk-meal-planner:
    if: ${{contains(steps.get-affected-apps.outputs.affected_apps,'aws-cdk-meal-planner')}}
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20
    steps:
      - run: npx nx run aws-cdk-meal-planner:deploy
